### ISSUE TITLE
automating the runbooks

### ISSUE THREAD

**Issue by SyCode7** [aws-samples/aws-incident-response-runbooks#1]
Thank you very much for these run books. I am working on automating incident response and I was wondering how much of these can be automated.  I have a program that can automate about `50%`, it will be very nice to translate some of the action into a `cloudformation ` or `terrafrom` for example. Users will appreciate the effort extremely well.

**Comment by phillisf** [comment]
Hi there,

Thanks for the feedback. I'm sure some of this can be automated but I can't give an exact percentage. Generally things where there are a well defined set of steps relating to an IT service, that also has an API, and where the types of output can be known (or at least handled) in a predictable fashion are good candidates for automation.

Just a note on your suggestion, most likely CloudFormation would deploy the infrastructure that would make your incident response automation possible. The *actual* incident response would be handled by that infrastructure, once deployed.

Was there any other input you were after? Please let me know, otherwise I'll go ahead and close this issue. Best of luck with it.

**Comment by SyCode7** [comment]
@phillisf cool, thank you for your response. Nothing more at this time, cheers.
